services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: app123
      POSTGRES_DB: restaurant_db
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d restaurant_db || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    ports: ["6379:6379"]

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports: ["8081:80"]
    depends_on: [postgres]
    restart: unless-stopped

  gateway:
    image: nginx:alpine
    container_name: api_gateway
    ports:
      - "8080:80" # Всі запити будуть йти сюди!
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - menusvc
      - authservice
      - order-dispatch-service
      - deliveryservice

  menusvc:
    build:
      context: ./API/MenuService
      dockerfile: Dockerfile
    environment:
      # <- якщо у MenuService в коді GetConnectionString("DefaultConnection") – лишай як є
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=restaurant_db;Username=appuser;Password=app123
      - Redis__ConnectionString=redis:6379
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports: ["5045:80"]

  order-dispatch-service:
    build:
      context: ./API/OrderDispatchService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=dispatch_db;Username=appuser;Password=app123
      - MenuService__BaseUrl=http://menusvc
      - DeliveryService__BaseUrl=http://deliveryservice:80
    depends_on:
      - postgres
      - menusvc
    ports:
      - "5245:80"

  authservice:
    build:
      context: ./API/AuthService  # Переконайтеся, що папка називається AuthService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      # Рядок підключення для AuthDb, який ми вказали в Program.cs
      - ConnectionStrings__AuthDb=Host=postgres;Port=5432;Database=authdb;Username=appuser;Password=app123
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5210:80"
    restart: unless-stopped

  deliveryservice:
    build:
      context: ./API/DeliveryService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DeliveryDb=Host=postgres;Port=5432;Database=delivery_db;Username=appuser;Password=app123
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5300:80" # Новий порт
    restart: unless-stopped

volumes:
  pgdata:
