name: Backend Services CI (Publish)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'API/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [AuthService, DeliveryService, MenuService, OrderDispatchService]

    steps:
    - uses: actions/checkout@v4

    # 1. Логінимося в DockerHub (використовуючи секрети)
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 2. Збираємо і Пушимо
    - name: Build and Push Docker image
      shell: bash
      run: |
        # Перетворюємо назву сервісу в маленькі літери (AuthService -> authservice)
        SERVICE_NAME=$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]')
        
        # Формуємо повну назву образу: юзернейм/назва-сервісу:тег
        # :latest означає "остання версія"
        IMAGE_TAG="${{ secrets.DOCKERHUB_USERNAME }}/$SERVICE_NAME:latest"
        
        echo "Building and Pushing $IMAGE_TAG..."
        
        # Збираємо (build)
        docker build . -t $IMAGE_TAG
        
        # Відправляємо в хмару (push)
        docker push $IMAGE_TAG
      working-directory: ./API/${{ matrix.service }}