name: Android Client CI

on:
  workflow_dispatch:

  push:
    branches: ["main"]
    paths:
      - 'ClientSide/UkrainianStyleRestaurant_2.0_another/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'ClientSide/UkrainianStyleRestaurant_2.0_another/**'

jobs:
  build-android:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ClientSide/UkrainianStyleRestaurant_2.0_another
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create google-services.json
        run: |
          echo "${{ secrets.CLIENT_GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d > app/google-services.json

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: client-app-debug
          path: ClientSide/UkrainianStyleRestaurant_2.0_another/app/build/outputs/apk/debug/app-debug.apk

      - name: Send APK to Telegram
        if: success()
        run: |
          APK_PATH="app/build/outputs/apk/debug/app-debug.apk"
          
          if [ -f "$APK_PATH" ]; then
            echo "File found. Sending to Telegram..."
            
            curl -v -F "chat_id=${{ secrets.TELEGRAM_TO }}" \
                 -F "caption=ðŸš€ Project: Client App | Build: Success âœ… | Branch: ${{ github.ref_name }}" \
                 -F "document=@$APK_PATH" \
                 https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument
          else
            echo "Error: APK file not found at $APK_PATH"
            exit 1
          fi
